setOnActuator(playerAct(player(player(answerA(X))))):-
setOnActuator(playerAct(player(player(answerB(X))))):-
setOnActuator(playerAct(player(player(answerC(X))))):-
%trunkLine1(trunkSpawnerLine1(trunkSpawner(spawnedComponents(X,trunk(posX(V)))))).
%trunkLine1(trunkSpawnerLine1(trunkSpawner(spawnedComponents(X,trunk(posZ(V)))))).
%trunkLine1(trunkSpawnerLine1(trunkSpawner(spawnedComponents(X,trunk(dim(V)))))).
%trunkLine2(trunkSpawnerLine2(trunkSpawner(spawnedComponents(X,trunk(posX(V)))))).
%trunkLine2(trunkSpawnerLine2(trunkSpawner(spawnedComponents(X,trunk(posZ(V)))))).
%trunkLine2(trunkSpawnerLine2(trunkSpawner(spawnedComponents(X,trunk(dim(V)))))).
%trunkLine3(trunkSpawnerLine3(trunkSpawner(spawnedComponents(X,trunk(posX(V)))))).
%trunkLine3(trunkSpawnerLine3(trunkSpawner(spawnedComponents(X,trunk(posZ(V)))))).
%trunkLine3(trunkSpawnerLine3(trunkSpawner(spawnedComponents(X,trunk(dim(V)))))).
%turtleLine1(tSpawnerLine1(turtleSpawner(spawnedComponents(X,turtle(posX(V)))))).
%turtleLine1(tSpawnerLine1(turtleSpawner(spawnedComponents(X,turtle(posZ(V)))))).
%turtleLine2(tSpawnerLine2(turtleSpawner(spawnedComponents(X,turtle(posX(V)))))).
%turtleLine2(tSpawnerLine2(turtleSpawner(spawnedComponents(X,turtle(posZ(V)))))).
%lineCars1(lineCars1(scrollLine(dir(value(X))))).
%lineCars1(lineCars1(scrollLine(carComponents(X,car(posX(V)))))).
%lineCars1(lineCars1(scrollLine(carComponents(X,car(posZ(V)))))).
%lineCars2(lineCars2(scrollLine(dir(value(X))))).
%lineCars2(lineCars2(scrollLine(carComponents(X,car(posX(V)))))).
%lineCars2(lineCars2(scrollLine(carComponents(X,car(posZ(V)))))).
%lineCars3(lineCars3(scrollLine(dir(value(X))))).
%lineCars3(lineCars3(scrollLine(carComponents(X,car(posX(V)))))).
%lineCars3(lineCars3(scrollLine(carComponents(X,car(posZ(V)))))).
%lineCars4(lineCars4(scrollLine(dir(value(X))))).
%lineCars4(lineCars4(scrollLine(carComponents(X,car(posX(V)))))).
%lineCars4(lineCars4(scrollLine(carComponents(X,car(posZ(V)))))).
%lineSuperCar(lineSuperCar(scrollLine(dir(value(X))))).
%lineSuperCar(lineSuperCar(scrollLine(carComponents(X,car(posX(V)))))).
%lineSuperCar(lineSuperCar(scrollLine(carComponents(X,car(posZ(V)))))).
%playerSensor(player(player(posX(X)))).
%playerSensor(player(player(posZ(X)))).
%goal1(goal1(goal(empty(X)))).
%goal1(goal1(goal(posX(X)))).
%goal1(goal1(goal(posZ(X)))).
%goal2(goal2(goal(empty(X)))).
%goal2(goal2(goal(posX(X)))).
%goal2(goal2(goal(posZ(X)))).
%goal3(goal3(goal(empty(X)))).
%goal3(goal3(goal(posX(X)))).
%goal3(goal3(goal(posZ(X)))).
%goal4(goal4(goal(empty(X)))).
%goal4(goal4(goal(posX(X)))).
%goal4(goal4(goal(posZ(X)))).
%goal5(goal5(goal(empty(X)))).
%goal5(goal5(goal(posX(X)))).
%goal5(goal5(goal(posZ(X)))).
